gateway:
  deployable-mcp-servers:
    test-mcp-server:
      name: deploy-test-mcp-server
      command: bash
      arguments: gradlew test-mcp-server:build -x test
      directory: {{PARENT_DIR}}
      copy-to-artifact-path: {{PROJ_DIR}}/ctx_bin
      copy-from-artifact-path: {{PARENT_DIR}}/test-mcp-server/build/libs/test-mcp-server.jar
      mcp-deploy-log: {{PROJ_DIR}}/test-mcp-server.log
      stdio: true
  mcp-http-servers-json-location: file:{{BUILD_DIR}}/resources/main/http-mcp-servers/servers-inttest.json
  mcp-stdio-servers-json-location: file:{{BUILD_DIR}}/resources/main/stdio-mcp-servers/servers-inttest.json