gateway:
  deployable-mcp-servers:
    test-mcp-server:
      name: deploy-test-mcp-server
      command: bash
      arguments: gradlew test-mcp-server:build -x test
      directory: {{PARENT_DIR}}
      copy-to-artifact-path: {{PROJ_DIR}}/ctx_bin
      copy-from-artifact-path: {{PARENT_DIR}}/test-mcp-server/build/libs/test-mcp-server.jar
      stdio: true
      mcp-deploy-log: {{PROJ_DIR}}/test-mcp-server.log
  mcp-http-servers-json-location: file:{{BUILD_DIR}}/resources/main/http-mcp-servers/servers-clienttest.json
  mcp-stdio-servers-json-location: file:{{BUILD_DIR}}/resources/main/stdio-mcp-servers/servers-clienttest.json
server.port: 8081

logging.config: classpath:logback-mcp-tool-gateway.xml

spring:
  docker:
    compose:
      enabled: false
      file: file:{{PROJ_DIR}}/src/main/resources/docker/docker-compose.yml
      skip:
        in-tests: true
      lifecycle-management: start_only
      start:
        skip: if_running
      readiness:
        wait: only_if_started


